-- Migration 000041 tokenized every text against the dictionary once and
-- added what it found missing, but a second pass over the *updated*
-- dictionary turned up a batch of extremely high-frequency single-character
-- words (到, 们, 与, 给, 时间, 对, 它, 他们...) that had been missing from
-- the very start — each was just never a "gap" on its own before because it
-- always happened to sit next to some other word inside a longer compound.
-- 到 alone appears bare (not as part of a compound) 27 times across the 52
-- texts, 们 25 times, 给 20 times, and so on.
INSERT INTO words (hanzi, pinyin, translation, part_of_speech, hsk_level) VALUES
('到', 'dào', 'прибывать; до, к (месту/времени)', 'verb', 1),
('们', 'men', 'суффикс множественного числа', 'particle', 1),
('给', 'gěi', 'давать; для, кому', 'preposition', 1),
('时间', 'shíjiān', 'время', 'noun', 1),
('两', 'liǎng', 'два', 'numeral', 1),
('对', 'duì', 'правильный; по отношению к', 'adjective', 1),
('要', 'yào', 'хотеть; нужно', 'verb', 1),
('学', 'xué', 'учиться', 'verb', 1),
('它', 'tā', 'оно', 'pronoun', 1),
('他们', 'tāmen', 'они', 'pronoun', 1),
('车', 'chē', 'машина, повозка', 'noun', 1),
('前', 'qián', 'перед', 'noun', 1),
('床', 'chuáng', 'кровать', 'noun', 1),
('走', 'zǒu', 'идти, ходить', 'verb', 1),
('玩儿', 'wánr', 'играть, гулять', 'verb', 1),
('饭', 'fàn', 'еда, рис', 'noun', 1),
('可', 'kě', 'можно, мочь', 'verb', 2),
('出', 'chū', 'выходить, появляться', 'verb', 2),
('地', 'de', 'суффикс наречия', 'particle', 2),
('次', 'cì', 'раз (счётное слово)', 'measure_word', 2),
('话', 'huà', 'речь, слова', 'noun', 2),
('位', 'wèi', 'счётное слово (вежливое, для людей)', 'measure_word', 2),
('打', 'dǎ', 'бить; играть (в игру)', 'verb', 2),
('样', 'yàng', 'вид, похожий', 'noun', 2),
('变', 'biàn', 'меняться', 'verb', 3),
('如何', 'rúhé', 'как', 'pronoun', 4),
('化', 'huà', 'суффикс «-изация»', 'particle', 5),
('时', 'shí', 'когда, время', 'noun', 4),
('性', 'xìng', 'суффикс «-ость», природа', 'particle', 5),
('失', 'shī', 'терять (в составе слов)', 'verb', 5),
('成', 'chéng', 'становиться', 'verb', 3),
('够', 'gòu', 'достаточно', 'adverb', 3),
('于', 'yú', 'в, на (книжный предлог)', 'preposition', 4),
('所', 'suǒ', 'место; то, что (грам. конструкция)', 'particle', 4),
('之', 'zhī', 'классическая притяжательная частица', 'particle', 5),
('正', 'zhèng', 'как раз, именно', 'adverb', 3),
('者', 'zhě', 'суффикс «тот, кто...»', 'particle', 4),
('被', 'bèi', 'показатель страдательного залога', 'particle', 3),
('养', 'yǎng', 'воспитывать; содержать (питомца)', 'verb', 3),
('另', 'lìng', 'другой', 'pronoun', 4),
('行', 'xíng', 'идти; ладно, можно', 'verb', 3),
('或', 'huò', 'или', 'conjunction', 3),
('力', 'lì', 'сила', 'noun', 4),
('式', 'shì', 'суффикс «модель, тип»', 'particle', 5),
('南方', 'nánfāng', 'юг', 'noun', 3),
('全', 'quán', 'весь, полностью', 'adverb', 3),
('称', 'chēng', 'называть', 'verb', 5),
('身', 'shēn', 'тело', 'noun', 3),
('当', 'dāng', 'быть (кем-л.); когда', 'verb', 3),
('消费', 'xiāofèi', 'потребление; тратить', 'verb', 4),
('内', 'nèi', 'внутри', 'noun', 3),
('一切', 'yíqiè', 'всё', 'pronoun', 4),
('满', 'mǎn', 'полный', 'adjective', 3),
('街', 'jiē', 'улица', 'noun', 3),
('弹', 'tán', 'играть (на муз. инструменте)', 'verb', 3),
('叶', 'yè', 'лист', 'noun', 4),
('活', 'huó', 'жить', 'verb', 3),
('盘', 'pán', 'тарелка (счётное слово)', 'measure_word', 3),
('身边', 'shēnbiān', 'рядом, около (кого-л.)', 'noun', 4),
('增加', 'zēngjiā', 'увеличивать', 'verb', 4),
('收', 'shōu', 'получать, принимать', 'verb', 3),
('边', 'biān', 'сторона, край', 'noun', 3),
('之间', 'zhījiān', 'между', 'noun', 4),
('过程', 'guòchéng', 'процесс', 'noun', 4),
('失去', 'shīqù', 'терять, лишаться', 'verb', 4);
